### PR TITLE
Created directory for translations and added file to it.

### PR DESCRIPTION
**Pull request by rheangocle**
Let me know how this looks. I added the translated day 3 to the new directory.

### CODE REVIEW

**Review by huytd — APPROVED** [review]

**Comment by huytd** [comment]
LGTM.

@nvh95 Do you have any other concern?

**Comment by nvh95** [comment]
LGTM as well.
We can update README to refer to this translation later.

**Review by nvh95 — APPROVED** [review]

**Comment by nvh95** [comment]
@rheangocle Thank you very much for your contributions 🥳❤️

**Comment by rheangocle** [comment]
Glad to help! I'll keep trying to translate the other docs as well

**Pull request merged**
